### ISSUE TITLE
File Upload web page is not working well on smartphone

### ISSUE THREAD

**Issue by deepkap** [xreef/ArduinoOTA_reusable_custom_web_page#2]
Progress bar, uploaded bytes count are working well on PC's browser.
But on Smartphone's browser progress bar is not updating frequently. During updating firmware uploaded bytes are showing 100% from starting.

**Comment by xreef** [comment]
Hi deepkap,
I try It, and it works well, but pay attention; it's very fast.


https://user-images.githubusercontent.com/1850282/196118504-96d772e2-b43a-465b-85e9-ec831e6ac159.mp4
